# Generated by Django 4.0.10 on 2024-01-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='invoice',
        ),
        migrations.AddField(
            model_name='items',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoices'),
        ),
    ]
