# Generated by Django 4.0.10 on 2024-01-06 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_remove_items_invoice_items_invoices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='invoices',
            new_name='invoice',
        ),
    ]
